### ISSUE TITLE
java.lang.NoSuchMethodError: 'double kotlin.time.Duration$Companion.getZERO-UwyO8pc()'

### ISSUE THREAD

**Issue by JustinBis** [Kotlin/kotlinx.coroutines#2350]
When upgrading a project's coroutine library version from 1.3.7 to 1.4.0, our Robolectric tests fail at runtime with a `NoSuchMethodError` when trying to access `Duration.ZERO`. We currently build with Kotlin 1.3.70, which includes `Duration.ZERO`, so I'm not sure why this is happening. 

This issue appeared here as well: https://github.com/kotest/kotest/issues/1509. In that case, they were building with Kotlin 1.4-M2.

Full stack trace:
```kotlin
java.lang.NoSuchMethodError: kotlin.time.Duration$Companion.getZERO-UwyO8pc()D
	at kotlinx.coroutines.DelayKt.toDelayMillis-LRDsOJo(Delay.kt:153)
	at kotlinx.coroutines.TimeoutKt.withTimeout-lwyi7ZQ(Timeout.kt:72)
	at com.my.company.project.CoroutinesExtensionsKt$dispatch$2.invokeSuspend(CoroutinesExtensions.kt:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

The code causing this looks like:

```kotlin
suspend fun tryDispatch(duration: Duration, block: suspend CoroutineScope.() -> T): T? =
    withContext(Dispatchers.IO) {
      withTimeout(duration) {
        try {
          block(this)
        } catch (e: Exception) {
          null
        }
      }
    }
```

The solution for us was to change `withTimeout(duration)` to `withTimeout(duration.toLongMilliseconds())` (same solution as the linked issue above). However, this should work with Duration directly as well.

**Comment by JustinBis** [comment]
This also occurs when calling the standard `delay` function with a `Duration`. Same fix there: `delay(duration.toLongMilliseconds())`.

**Comment by mickael-menu** [comment]
Possibly related: https://github.com/Kotlin/kotlinx.coroutines/issues/2353

**Comment by eygraber** [comment]
We had this issue when updating to Kotlin 1.4 as well. I don't remember the exact problem, but it was related to a transient dependency on an older version of Kotlin (and possibly using an older style of artifact). 

We fixed it by updating all our dependencies (direct and transient) to versions that use Kotlin 1.4 (some of them were in progress and we just had to wait for a release, others we had to open PRs to get things moving).

**Comment by qwwdfsad** [comment]
@JustinBis does Kotlin update help you? We've changed the mangling scheme of inline classes in Kotlin 1.4.0, so 1.3.x Kotlin sneaked into the classpath is likely to be an issue

**Comment by JustinBis** [comment]
@qwwdfsad, that turned out to be exactly the issue and @eygraber has the right fix. Ultimately, we had to upgrade a lot of dependencies at the same time as upgrading the coroutines library, and we had to switch to compiling our code with Kotlin 1.4.
