### ISSUE TITLE
java.lang.NoSuchMethodError 0.21 -> 0.24.0

### ISSUE THREAD

**Issue by tagantroy** [Kotlin/kotlinx.coroutines#468]
I tried migrate from 0.21 to 0.24.0 and got 
`java.lang.NoSuchMethodError: kotlinx.coroutines.experimental.BuildersKt.launch$default(Lkotlin/coroutines/experimental/CoroutineContext;Lkotlinx/coroutines/experimental/CoroutineStart;Lkotlinx/coroutines/experimental/Job;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function2;ILjava/lang/Object;)Lkotlinx/coroutines/experimental/Job;`
kotlin compiler 1.2.51
I can provide link to sources.

**Comment by qwwdfsad** [comment]
Please provide link to sources

**Comment by tagantroy** [comment]
@qwwdfsad Hello.
https://github.com/Malinskiy/marathon/blob/upgrade_kotlin_coroutines_to_0_24_0/vendor-android/src/main/kotlin/com/malinskiy/marathon/android/AndroidDeviceProvider.kt

**Comment by qwwdfsad** [comment]
Hi, could you please elaborate on how to reproduce the problem?
All tests pass in `upgrade_kotlin_coroutines_to_0_24_0` branch.
Moreover, required method is present: https://github.com/Kotlin/kotlinx.coroutines/blob/master/binary-compatibility-validator/reference-public-api/kotlinx-coroutines-core.txt#L35

Probably it's problem with project dependencies, not with binary compatibility

**Comment by tagantroy** [comment]
@qwwdfsad Hello, After upgrade gradle to 4.10-rc1 with bundled Kotlin 1.2.60 it works fine.
