### ISSUE TITLE
Unresolved reference kotlinx in commonMain with version 1.7.3 (works correctly with 1.7.2)

### ISSUE THREAD

**Issue by langara** [Kotlin/kotlinx.coroutines#3841]
**Describe the bug**

Compilation error when using kotlinx-coroutines ver 1.7.3 in commonMain source set.

**Provide a Reproducer**

https://github.com/langara/reproducers/tree/main/reproduce-02-coroutines-mp

It's basically the same as smokeTest from kotlinx-coroutines:
https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration-testing/smokeTest

**Comment by qwwdfsad** [comment]
For some reason, it's not reproducible locally on my machine on your project.
Could you please ensure it's still the case and that you don't have `kotlin.mpp.enableCompatibilityMetadataVariant` set to `true` in your properties

**Comment by langara** [comment]
Thanks for checking. I just checked on github runner, and it works correctly there, then I removed some old stuff from mavenLocal (from /home/marek/.m2/repository/org/jetbrains/kotlinx), and now it works correctly on my machine too.
So I guess this issue should be closed because it was just a problem with my machine. Unless there is some easy way to make such errors less misleading.
