### ISSUE TITLE
Crash when collecting a combined MutableStateFlow<Duration>

### ISSUE THREAD

**Issue by mickael-menu** [Kotlin/kotlinx.coroutines#2353]
Using the latest version of Kotlin (1.4.10) and coroutines (1.4.0), I get a confusing crash when attempting to combine a `MutableStateFlow<Duration>`.

[See the code producing the issue in a Kotlin Playground.](https://pl.kotl.in/njxdnz_SG)

Sample code:

```kotlin
val durationFlow = MutableStateFlow(Duration.ZERO)
val incrementFlow = MutableStateFlow(Duration.ZERO)

launch {
    combine(durationFlow, incrementFlow) { duration, increment -> duration + increment }
        .collect {
            Log.e("Flow", "Collected $it")
        }
}

incrementFlow.value = 5.seconds
```

Stacktrace:

```
    java.lang.ClassCastException: kotlin.time.Duration cannot be cast to java.lang.Number
        at MainActivity$onCreate$1$1.invoke(Unknown Source:0)
        at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$unsafeFlow$1$lambda$1.invokeSuspend(Zip.kt:33)
        at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$unsafeFlow$1$lambda$1.invoke(Unknown Source:14)
        at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:79)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

A similar code used to work earlier for me, but I couldn't pinpoint in which versions.

I wonder if this is because `Duration` is an inline class, because using `String` instead works perfectly:

```kotlin
val stringFlow = MutableStateFlow("")
val incrementFlow = MutableStateFlow("")

launch {
    combine(stringFlow, incrementFlow) { string, increment -> string + increment }
        .collect {
            Log.e("Flow", "Collected $it")
        }
}

incrementFlow.value = "a"

```

**Comment by Augusent** [comment]
Faced the same issue after updating coroutines from **1.4.0-M1** to 1.4.0 (and 1.4.1 as well). In my case, I get `java.lang.NoSuchMethodError` but the inline class type is nullable.

Apparently, the issue is not directly related to `combine` since I got the same `NoSuchMethodError`/`ClassCastException` for `zip`.

Here's a reproducer with both scenarios: https://pl.kotl.in/UUx3gBmiX

**Comment by mickael-menu** [comment]
Thanks for weighing in @Augusent, I created a playground showcasing my error as well:

https://pl.kotl.in/njxdnz_SG

**Comment by ilmirus** [comment]
@mickael-menu Thanks, reproduced: https://youtrack.jetbrains.com/issue/KT-43249. This is clearly compiler bug(s). And yes, this is because `Duration` is an inline class.

**Comment by b95505017** [comment]
@elizarov Sorry, why closing this issue? Does it fix?

**Comment by Shusek** [comment]
After update to kotlin 1.5.0 and coroutines 1.5.0 the error happen again.
