### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError kotlinx.coroutines.reactive.FlowSubscription when updating kotlinx-coroutines from 1.3.7 to 1.3.9

### ISSUE THREAD

**Issue by mdoh** [Kotlin/kotlinx.coroutines#2250]
Dear Kotlin-team,

I m having a rective spring-boot project (spring-boot version 2.3.3.). 
I updated Kotlin to version 1.4 and kotlinx-coroutines-core and kotlinx-coroutines-reactor to 1.3.9.

I am using spring-boot webclient to retrieve data.

`        return WebClient.create(url)
                .get()
                .retrieve()
                .bodyToFlow()`

after I updated I am getting this exception: 

`Caused by: java.lang.NoSuchMethodError: kotlinx.coroutines.reactive.FlowSubscription.<init>(Lkotlinx/coroutines/flow/Flow;Lorg/reactivestreams/Subscriber;Lkotlin/coroutines/CoroutineContext;)V
	at kotlinx.coroutines.reactor.FlowAsFlux.subscribe(ReactorFlow.kt:39)
	at org.springframework.http.server.reactive.ChannelSendOperator.subscribe(ChannelSendOperator.java:77)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at kotlinx.coroutines.reactor.MonoCoroutine.onCompleted(Mono.kt:66)
	at kotlinx.coroutines.AbstractCoroutine.onCompletionInternal(AbstractCoroutine.kt:104)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:294)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:333)`

In kotlinx-coroutines-core and kotlinx-coroutines-reactor to 1.3.7. it is working as expected.

**Comment by elizarov** [comment]
Please, check in `gradlew dependencies`  what versions of other `kotlinx.coroutines` modules you end up getting in your project.

**Comment by 1nDivid** [comment]
Same here. Just updated to 1.3.9 and got NoSuchMethodError

<img width="568" alt="image" src="https://user-images.githubusercontent.com/3629830/93792344-13e26f00-fc3e-11ea-86e3-9277d4527e46.png">

**Comment by 1nDivid** [comment]
Made a few tests and found that problem with .asFlow extension function.

**Comment by elizarov** [comment]
The picture clearly shows that you have `kotlinx-coroutines-core:1.3.9` and `kotlinx.coroutines-reactive:1.3.8`. It is not designed to work this way. Versions of different modules must match.

**Comment by 1nDivid** [comment]
Yeap, i've specified version of coroutines-reactive and problem has gone.

**Comment by MrBuddyCasino** [comment]
I have just hit the same error on upgrading to 1.3.9, and the problems was that `kotlinx-coroutines-reactive:1.3.3` was somehow ending up in my classpath. The only way to fix it was to explicitly pull in the 1.3.9 version as well:

```
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:${property("coroutinesVersion")}")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor:${property("coroutinesVersion")}")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactive:${property("coroutinesVersion")}")
```
