### ISSUE TITLE
Incompatible BOM/Dependency mismatches: java.lang.NoSuchMethodError: void kotlinx.coroutines.test.TestBuildersKt.runTest

### ISSUE THREAD

**Issue by NoPhaseNoKill** [Kotlin/kotlinx.coroutines#3951]
The first issue: 
- Disclaimer: am fairly new to setting up build systems, so excuse my lack of knowledge if it turns out to be an issue on my end
- Am getting the attached error when bumping version 1.6.4 to 1.7.3 inside of a multi-module gradle project, and running ./gradlew test on a repo which can be found here: https://github.com/NoPhaseNoKill/IntegraBoost/tree/coroutine-error
- It looks as though the kotlinx-couroutines-bom isn't working as intended when using this new version, but am unfamiliar with what's going on under the covers after having read the file/what it does
- Similar issues look like they were introduced around 1.7.0: https://github.com/Kotlin/kotlinx.coroutines/issues/3673
- It is a shared depedency across modules

```
java.lang.NoSuchMethodError: 'void kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0$default(kotlin.coroutines.CoroutineContext, long, kotlin.jvm.functions.Function2, int, java.lang.Object)'
	at com.integraboost.extensions.TestInvocationListener.interceptTestMethod(TestInvocationListener.kt:32)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:202)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

Now broken resolved dependencies (1.7.3)
- Attachment of integraBoostLibrary resolved dependencies (1.7.3 - broken)

![image](https://github.com/Kotlin/kotlinx.coroutines/assets/4100222/843ee0b0-7485-44d7-bef6-2b9ad28b1213)

-  Attachment of integraBoostService resolved depdencies (1.7.3 - broken) <------ Notice the mismatch in versions
![image](https://github.com/Kotlin/kotlinx.coroutines/assets/4100222/81b16c30-413b-4c29-a981-f8cf0f8dec1e)

Previously working resolved dependencies (1.6.4)
- Attachment of integraBoostLibrary resolved dependencies (1.6.4 - works)

![image](https://github.com/Kotlin/kotlinx.coroutines/assets/4100222/a4826ff7-0edd-4c25-a00f-97295f12bcde)

-  Attachment of integraBoostService resolved depdencies (1.6.4 - works)
![image](https://github.com/Kotlin/kotlinx.coroutines/assets/4100222/05881c84-3a0a-4796-8b9f-e75b196db389)

How to reproduce:
- Branch to checkout: https://github.com/NoPhaseNoKill/IntegraBoost/tree/coroutine-error
- Run ./gradlew test from the root directory
- Commit showcasing differences: https://github.com/NoPhaseNoKill/IntegraBoost/commit/d69774de8de10dd95ca02904178d350b0d6bc637
- If you need to see the old behaviour from version 1.6.4, just checkout master, and run ./gradlew test from the root directory again

The second issue:
- Checkout the branch here: https://github.com/NoPhaseNoKill/IntegraBoost/tree/kotlin-plugin-dependency-issue
- When bumping the kotlin version plugin to kotlin("jvm") version "1.9.20" (previously was:  kotlin("jvm") version "1.8.20"), there seems to be conflicts with some of the kotlin stdlib, as shown here:

![image](https://github.com/Kotlin/kotlinx.coroutines/assets/4100222/e7592e9f-8cee-4d39-bd4a-5423334f5570)

Let me know if you need anything else

**Comment by dkhalanskyjb** [comment]
Sorry, I don't know anything about how to work with Spring Boot, so I can't give any meaningful advice. This is an issue tracker for problems in kotlinx-coroutines. To get help with your build setup, please use Kotlin Slack or Stack Overflow.

That said, it looks like there is a separate classpath that Spring Boot uses, and you need to find some way to influence it. The easiest way to fix your immediate concern is to edit `modules/integraBoostService/build.gradle.kts` and change the Spring Boot version from 3.1.5 to 3.2.2 (and with it, the version of coroutines on which Spring Boot depends), but I think the problem of needing to set the Spring Boot classpath will come back eventually, so it's worth investigating how to solve this properly.

As for your second issue, the URL returns 404.
