### ISSUE TITLE
NoClassDefFoundError: kotlinx.coroutines.android.HandlerContextKt

### ISSUE THREAD

**Issue by YMZ1994420** [Kotlin/kotlinx.coroutines#793]
After update kotlin version to 1.3.0.I add follow to gradle:
```
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.0.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.0.0'
    implementation "org.jetbrains.anko:anko:$anko_version"
```
but in  runtime,throw exception:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.konka.remoteservice, PID: 30643
    java.lang.NoClassDefFoundError: kotlinx.coroutines.android.HandlerContextKt
        at org.jetbrains.anko.sdk27.coroutines.Sdk27CoroutinesListenersWithCoroutinesKt.onClick$default(ListenersWithCoroutines.kt:293)
        at com.konka.remoteservice.activity.MainActivity.onCreate(MainActivity.kt:33)
        at android.app.Activity.performCreate(Activity.java:5288)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5001)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by YMZ1994420** [comment]
I already update the IDE kotlin plugin to .13.But not work

**Comment by 35penguins** [comment]
FYI I also received this error when using Kotlin 1.3, kotlinx coroutines '1.0.0' with Anko '0.10.7-rc13'.. if I downgrade kotlinx coroutines to '0.30.2-eap13', I no longer see this error...

**Comment by Korcholis** [comment]
I just tested it out. The new Anko [1.0.8](https://github.com/Kotlin/anko/releases/tag/v0.10.8) works with Kotlin 1.3 and coroutines 1.0.0

**Comment by simi-aluko** [comment]
project works now with kotlin version 1.3.50 and with anko version 0.10.8

**Comment by tushars0** [comment]
project works with anko:anko:0.10.8,   kotlinOptions -> apiVersion = '1.3', kotlin_version = '1.4.10'

**Comment by CATAWDE** [comment]
project work:   
 anko:anko:0.10.8, 
kotlinOptions -> apiVersion = '1.2'  or '1.3',
 kotlin_version = '1.4.10'
